version: 2.1
orbs:
  go: circleci/go@1.7.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor:
      name: go/default
      tag: '1.21.3'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git:
          force: true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: staging
